# Project
version=1.0
group=redstonedubstep.mods.playernamemodifier
java_version=25

# Common
minecraft_version=26.1.1
mod_name=PlayerNameModifier
mod_author=Redstone_Dubstep
mod_id=playernamemodifier
license=C0-1.0
credits=
description=A mod that allows changing a player's display name using vanilla tags, lightweight and fully configurable
minecraft_version_range=[26.1.1,)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.1-1

# Fabric
fabric_version=0.145.3+26.1.1
fabric_loader_version=0.18.6

# NeoForge
neoforge_version=26.1.1.2-beta
neoforge_loader_version_range=[4,)

# Dependencies
fcap_version=26.1.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
